avalongod/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/urls.py
from django.urls import path
from . import views

# add the names in base_generic.html sidebar block
urlpatterns = [
    path('', views.index, name='index'),
    path('players/', views.PlayerListView.as_view(), name='players'),
    path('vision/merlin/', views.MerlinVisionView.as_view(), name='merlin-vision'),
    path('vision/percival/', views.PercivalVisionView.as_view(), name='percival-vision'),
    path('vision/morgana/', views.MorganaVisionView.as_view(), name='morgana-vision'),
    path('vision/badrole/', views.BadRoleVisionView.as_view(), name='badrole-vision'),
    path('player/<str:pk>', views.PlayerDetailView.as_view(), name='player-detail'),
    path('rooms/', views.RoomListView.as_view(), name='rooms'),
    path('room/<str:pk>', views.RoomDetailView.as_view(), name='room-detail'),
]
urlpatterns += [
    path('myrole/', views.RoleVisionUserListView.as_view(), name='my-role'),
]
urlpatterns += [
    path('player/create/', views.PlayerCreate.as_view(), name='player-create'),
    path('player/<str:pk>/update/', views.PlayerUpdate.as_view(), name='player-update'),
    path('player/<str:pk>/delete/', views.PlayerDelete.as_view(), name='player-delete'),
    path('player/<str:pk>/vote/', views.VoteUpdate.as_view(), name='player-vote'),
    path('player/<str:pk>/action/', views.ActionUpdate.as_view(), name='player-action'),
]

urlpatterns += [
    path('room/create/', views.RoomCreate.as_view(), name='room-create'),
    path('room/<int:pk>/update/', views.RoomUpdate.as_view(), name='room-update'),
    path('room/<int:pk>/delete/', views.RoomDelete.as_view(), name='room-delete'),
]

urlpatterns += [
    path('mission/<int:pk>', views.mission, name='mission'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required

# Create your models here.
class Player(models.Model):
    """
    Model representing players
    """
    MERLIN = 'Merlin'
    PERCIVAL = 'Percival'
    SERVANT = 'Servant'
    MORGANA = 'Morgana'
    ASSASSIN = 'Assassin'
    MINIONS = 'Minion'
    OBERON = 'Oberon'
    MORDRED = 'Mordred'
    # Choices
    ROLE_CHOICES = [
        # good team
        (MERLIN, 'Merlin'),
        (PERCIVAL, 'Percival'),
        (SERVANT, 'Loyal Servant of Author'),
        # evil team
        (MORGANA, 'Morgana'),
        (ASSASSIN, 'Assassin'),
        (MINIONS, 'Minion of Mordred'),
        (OBERON, 'Oberon'),
        (MORDRED, 'Mordred'),
    ]
    VOTE_CHOICES = [
        ('agree', 'agree'),
        ('disagree', 'disagree'),
        ('hesitate...', 'hesitate...')
    ]
    ACTION_CHOICES = [
        ('PASS', 'PASS'),
        ('OUT', 'OUT'),
        ('FAIL', 'FAIL'),
    ]
    # Fields
    player_name = models.CharField(max_length=20, help_text="Player nick name", primary_key=True)
    id = models.PositiveIntegerField(help_text='seat id')
    role = models.CharField(max_length=20, help_text="Role of each player", choices=ROLE_CHOICES, default=SERVANT)
    room = models.ForeignKey('Room', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    vote = models.CharField(max_length=20, help_text="Choose 'agree' if the chief`s proposal sounds OK for you.", choices=VOTE_CHOICES, default='hesitate...')
    action = models.CharField(max_length=10, help_text='PASS if you decide to complete the mission. FAIL if you decide otherwise. OUT if you are not in the mission!', choices=ACTION_CHOICES, default='OUT')

    ...

    # Metadata
    class Meta:
        ordering = ["id"]
        permissions = (("room_holder", " set a player as a Room holder"),)

    # Methods
    def get_absolute_url(self):
        """
         Returns the url to access a particular instance of Player.
         """
        return reverse('player-detail', args=[str(self.player_name)])

    # check the role of player
    def is_Good(self):
        if self.role in ['Merlin', 'Percival', 'Servant']:
            return True
        return False

    def is_Merlin(self):
        if self.role == 'Merlin':
            return True
        return False

    def is_Percival(self):
        if self.role == 'Percival':
            return True
        return False

    def is_Servant(self):
        if self.role == 'Servant':
            return True
        return False

    def is_Evil(self):
        if self.role in ['Morgana', 'Assassin', 'Minion', 'Oberon', 'Mordred']:
            return True
        return False

    def is_Morgana(self):
        if self.role == 'Morgana':
            return True
        return False

    def is_Assassin(self):
        if self.role == 'Assassin':
            return True
        return False

    def is_Minion(self):
        if self.role == 'Minion':
            return True
        return False

    def is_Oberon(self):
        if self.role == 'Oberon':
            return True
        return False

    def is_Mordred(self):
        if self.role == 'Mordred':
            return True
        return False

    def is_Evil_but_Morgana(self):
        if self.role in ['Assassin', 'Minion', 'Mordred']:
            return True
        return False

    def vote_agree(self):
        if self.vote in ['agree']:
            return True
        return False

    def __str__(self):
        return f'{self.id} -- {self.player_name}'


class Room(models.Model):
    """Model representing rooms to play"""
    WAIT = 'WAIT'
    PLAY = 'PLAY'
    READY = 'READY'
    STATUS_CHOICES = [
        (WAIT, 'Waiting...'),
        (PLAY, 'Playing...'),
        (READY, 'Ready!')
    ]
    room_id = models.PositiveIntegerField(primary_key=True, help_text='Room id(e.g. 1234)')
    player_num = models.PositiveIntegerField(help_text='Players in the room', default=0)
    Lady_in_the_lake = models.BooleanField(help_text='Whether a lady in the lake is included in the game')
    max_num = models.ForeignKey('Rule', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=10, default=WAIT, help_text="Room status(waiting/playing/ready)", choices=STATUS_CHOICES)

    class Meta:
        ordering = ['room_id']

    def update_status(self):
        player_num = Player.objects.filter(room=self.room_id).count()
        self.player_num = player_num
        if self.status == 'WAIT':
            if player_num == self.max_num.rule_num:
                self.status = 'READY'
        self.save()
        return True

    def role_distribute(self):
        ROLES = self.max_num.roles.split()
        if self.status == 'READY':
            player_in_room = Player.objects.filter(room=self.room_id)
            for player in player_in_room:
                player.role, ROLES = pop_and_remove(ROLES)
                player.save()
            self.status = 'PLAY'
            self.save()
            return True
        return False

    def mission_result(self):
        if self.status == 'PLAY':
            player_in_room = Player.objects.filter(room=self.room_id)
            num_players = player_in_room.all().count()
            num_out = player_in_room.filter(action__iexact='OUT').count()
            num_mission = num_players - num_out
            num_pass = player_in_room.filter(action__iexact='PASS').count()
            num_fail = player_in_room.filter(action__iexact='FAIL').count()
            return self.room_id, num_players, num_mission, num_pass, num_fail
        else:
            return 0, 0, 0, 0


    def get_absolute_url(self):
        #Returns the url to access a particular instance of Room.
        return reverse('room-detail', args=[self.room_id])

    def __str__(self):
        return f'{self.room_id} : Max player: {self.max_num}'

    """
    def display_genre(self):
        #Create a string for the Genre. This is required to display genre in Admin.
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'
    """

class Rule(models.Model):
    """Rules for different number of players"""
    RULE_CHOICES = [
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
    ]
    rule_num = models.PositiveIntegerField(primary_key=True, help_text='Number of players', choices=RULE_CHOICES)
    tasks = models.CharField(max_length=20, help_text='Task Rule')
    roles = models.CharField(max_length=150, help_text='Roles for each player', null=True)

    class Meta:
        ordering = ['rule_num']

    def __str__(self):
        return f'{self.rule_num}'

import random
def pop_and_remove(items):
    if items:
        index = random.randrange(len(items))
        item = items.pop(index)
        return item, items
# run these commands each time the model changed:
# python manage.py makemigrations
# python manage.py migrate

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class RoleVisionForm(forms.Form):
    role_vision = forms.CharField(help_text="Input your role to check your vision.")

    def clean_role_vision(self):
        data = self.cleaned_data['role_vision']
        roles = ['merlin', 'percival', 'servant', 'morgana', 'assassin', 'minion', 'oberon', 'mordred']
        # check if data in roles
        if data.lower() not in roles:
            raise ValidationError(_('Invalid role! Please ckeck your spell.'))

        return data

class VoteForm(forms.Form):
    vote = forms.BooleanField(help_text="Input your vote descision.")

    def clean_vote(self):
        data = self.cleaned_data['vote']

        return data

class NameForm(forms.Form):
    name = forms.CharField(help_text="Input your name here.")

    def clean_name(self):
        data = self.cleaned_data['name']

        return data

catalog/views.py
from .models import Player, Room, Rule
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_players = Player.objects.all().count()
    num_rooms = Room.objects.all().count()
    # The 'all()' is implied by default.
    num_rules = Rule.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_players': num_players,
        'num_rooms': num_rooms,
        'num_rules': num_rules,
        'num_visits': num_visits
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class PlayerListView(generic.ListView):
    model = Player
    #context_object_name = 'Player'
    #template_name = 'players/player_list.html'
    paginate_by = 10

    def get_queryset(self):
        return Player.objects.all()
        #return Player.objects.filter(role__iexact='ML')[:10]

class MerlinVisionView(generic.ListView):
    model = Player
    paginate_by = 10
    template_name = 'catalog/merlin_list.html'

    def get_queryset(self):
        return Player.objects.filter(role__in=['Morgana', 'Assassin', 'Minion', 'Oberon'])

class PercivalVisionView(generic.ListView):
    model = Player
    paginate_by = 10
    template_name = 'catalog/percival_list.html'

    def get_queryset(self):
        return Player.objects.filter(role__in=['Merlin', 'Morgana'])

class MorganaVisionView(generic.ListView):
    model = Player
    paginate_by = 10
    template_name = 'catalog/morgana_list.html'

    def get_queryset(self):
        return Player.objects.filter(role__in=['Mordred', 'Assassin', 'Minion'])

class BadRoleVisionView(generic.ListView):
    model = Player
    paginate_by = 10
    template_name = 'catalog/badrole_list.html'

    def get_queryset(self):
        return Player.objects.filter(role__in=['Morgana', 'Assassin', 'Minion', 'Mordred'])

class RoomListView(generic.ListView):
    model = Room
    paginate_by = 10

    def get_queryset(self):
        return Room.objects.all()

class PlayerDetailView(generic.DetailView):
    model = Player

class RoomDetailView(generic.DetailView):
    model = Room

class RoleVisionUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = Player
    template_name ='catalog/role_vision_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Player.objects.filter(user=self.request.user)

class PlayerCreate(CreateView):
    model = Player
    fields = ['player_name', 'id', 'role', 'room', 'user']
    initial = {'room': '1000'}

class PlayerUpdate(UpdateView):
    model = Player
    fields = ['player_name', 'id', 'room', 'user']# Not recommended (potential security issue if more fields added)

class PlayerDelete(DeleteView):
    model = Player
    success_url = reverse_lazy('players')

class RoomCreate(CreateView):
    model = Room
    fields = ['room_id', 'Lady_in_the_lake', 'max_num']
    initial = {'Lady_in_the_lake': False}

class RoomUpdate(UpdateView):
    model = Room
    fields = ['room_id', 'Lady_in_the_lake', 'max_num']

class RoomDelete(DeleteView):
    model = Room
    success_url = reverse_lazy('rooms')

class VoteUpdate(UpdateView):
    model = Player
    fields = ['vote']
    success_url = reverse_lazy('my-role')

class ActionUpdate(UpdateView):
    model = Player
    fields = ['action']
    success_url = reverse_lazy('my-role')

@login_required
def mission(request, pk):
    """View function for home page of site."""
    room = get_object_or_404(Room, pk=pk)
    # Generate counts of some of the main objects
    room_id, num_players, num_mission, num_pass, num_fail = room.mission_result()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'room_id': room_id,
        'num_mission': num_mission,
        'num_pass': num_pass,
        'num_fail': num_fail,
        'num_visits': num_visits
    }

    return render(request, 'mission.html', context=context)

catalog/templates/catalog/badrole_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your play for the evil side.</h1>
    {% if player_list %}
    <ul>
      {% for player in player_list %}
          {% if player.is_Morgana %}
          <p>Morgana player:</p>
          <p>Name: {{ player.player_name }} || Seat at {{ player.id }} </p>
          {% else %}
          <p>Other evil side players:</p>
          <p>Name: {{ player.player_name }} || Seat at {{ player.id }} </p>
          {% endif %}
      {% endfor %}
    </ul>

    {% else %}
      <p>There is no vision! Something went wrong!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/merlin_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your role is: Merlin</h1>
    {% if player_list %}
    <ul>
    <h3>Bad guys except Mordred: </h3>
      {% for player in player_list %}
          <p>Name: {{ player.player_name }} || Seat at {{ player.id }} </p>
      {% endfor %}
    </ul>

    {% else %}
      <p>There is no vision! Something went wrong!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/morgana_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your role is: Morgana</h1>
    {% if player_list %}
    <ul>
    <h3>Other evil side players: </h3>
      {% for player in player_list %}
          <p>Name: {{ player.player_name }} || Seat at {{ player.id }} </p>
      {% endfor %}
    </ul>

    {% else %}
      <p>There is no vision! Something went wrong!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/percival_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your role is: Percival</h1>
    {% if player_list %}
    <ul>
    <h3>Merlin and Morgana: </h3>
      {% for player in player_list %}
          <p>Name: {{ player.player_name }} || Seat at {{ player.id }} </p>
      {% endfor %}
    </ul>

    {% else %}
      <p>There is no vision! Something went wrong!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/player_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Player</h1>

<p>Are you sure you want to delete the player: {{ player }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/player_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Player name: {{ player.player_name }}</h1>

  <!-- author detail link not yet defined -->
  <p><strong>id:</strong> {{ player.id }}</p>

  <div style="margin-left:20px;margin-top:20px">

    <h4>Room:</h4>
    <p><strong>room:</strong> <a href="{{ player.room.get_absolute_url }}">{{ player.room }}</a></p>
    {% for copy in player.room.all %}
      <hr>
      <p class="{% if copy.status == 'WAIT' %}text-success{% elif copy.status == 'PLAY' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'WAIT' %}
        <p><strong>Player number:</strong> {{ copy.player_num }}</p>
      {% endif %}
      <p><strong>Max number:</strong> {{ copy.max_num  }}</p>
      <p><strong>Room ID:</strong> {{ copy.room_id  }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/player_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/player_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Player List</h1>
  {% if player_list %}
  <ul>
    {% for player in player_list %}
      <h4>Player: {{player.player_name}}</h4>
      <li>
        <a href="{{ player.get_absolute_url }}">Detail</a>
      </li>
      <li>
        <a href="{% url 'player-update' player.pk %}">Update</a>
      </li>
      <li>
        <a href="{% url 'player-delete' player.pk %}">Delete</a>
      </li>
    {% endfor %} 
    <h1> </h1>
    <li>
        <a href="{% url 'player-create'%}">Create New Player</a>
    </li>
  </ul>
  {% else %}
    <p>There are no players now.</p>
  {% endif %} 
{% endblock %}

catalog/templates/catalog/role_vision.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your role is:</h1>

    {% if player_obj %}
    <ul>

      {% for player in player_list %}
      <li class="{% if player.is_Merlin %}text-danger{% endif %}">
        {% for p in player_list %}
        {% if player.Merlin_Vision %}
            <a href="{% url 'room-detail' player.room.pk %}">{{player.room}}</a> ({{ player.role}})
            <p>{{ player.player_name }} -- {{ player.id }}</p>
        {% endif %}
        {% endfor %}

      </li>
      <li class="{% if player.is_Morgana %}text-danger{% endif %}">
        <a href="{% url 'room-detail' player.room.pk %}">{{player.room}}</a> ({{ player.role}})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No role found. </p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/role_vision_user.html
{% extends "base_generic.html" %}

{% block content %}

    {% if player_list %}
    <ul>

      {% for player in player_list %}
      <li>
      <h2>In room:</h2>
        <a href="{% url 'room-detail' player.room.pk %}">{{player.room}}</a>
      <h5>Your role is: {{ player.role }}</h5>
        {% if player.is_Merlin %}
            <a href="{% url 'merlin-vision' %}">Your Vision</a>
        {% elif player.is_Percival %}
            <a href="{% url 'percival-vision' %}">Your Vision</a>
        {% elif player.is_Morgana %}
            <a href="{% url 'morgana-vision' %}">Your Vision</a>
        {% elif player.is_Evil_but_Morgana %}
            <a href="{% url 'badrole-vision' %}">Your Vision</a>
        {% endif %}
      </li>
          <p> </p>
      <li>
        <h3>Your current vote: {{ player.vote }}</h3>
        <p>Remember to change your vote each round.</p>
        <a href="{% url 'player-vote' player.pk %}">Renew Your Vote</a>
      </li>
          <p> </p>
      <li>
        <h3>Your current action: {{ player.action }}</h3>
        <p>OUT means you are not in the mission.</p>
        <p>PASS means you want the mission to pass.</p>
        <p>FAIL means you want the mission to fail.</p>
        <a href="{% url 'player-action' player.pk %}">Renew Your Action</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No role found. </p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/room_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Room</h1>

<p>Are you sure you want to delete the room: {{ room }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/room_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Room id: {{ room.room_id }}</h1>
  <p><strong>Max player number:</strong> {{ room.max_num }}</p>
  <p><strong>Lady in the lake: <font size="3" color="#ff8c00">{{ room.Lady_in_the_lake|yesno:'YES,NO,UNKNOWN' }}</font></strong> </p>
    <p><strong>status:</strong> <font size="3" color="#008b8b">{{ room.status }}</font></p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Players' Vote:</h4>

    {% for copy in room.player_set.all %}
      <hr>
      <p><strong>{{ copy.id }}.{{ copy.player_name }} Vote: </strong></p>
      <p class="{% if copy.vote_agree %}text-success{% else %}text-danger{% endif %}">
        {{ copy.get_vote_display }}
      </p>

    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/room_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/room_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Room List</h1>
  {% if room_list %}
  <ul>
    {% for room in room_list %}
        {% if room.update_status %}
      <h4>Room: {{room.room_id}}</h4>
      <h4>Room players count: {{room.player_num}}(Status: {{room.status}})</h4>
        {% endif %}
        {% if room.role_distribute %}
        <p>Each player should have a role now.</p>
        <p>It`s time to play!</p>
        {% endif %}
      <li>
        <a href="{{ room.get_absolute_url }}">Vote Result</a>
      </li>
      <li>
        <a href="{% url 'mission' room.pk %}">Mission Result</a>
      </li>
      <li>
        <a href="{% url 'room-update' room.pk %}">Update</a>
      </li>
      <li>
        <a href="{% url 'room-delete' room.pk %}">Delete</a>
      </li>
        <p></p>
    {% endfor %}
    <p></p>
    <li>
        <a href="{% url 'room-create'%}">Create New Room</a>
    </li>
  </ul>
  {% else %}
    <p>There are no rooms now.</p>
  {% endif %} 
{% endblock %}